sudo: required

env:
  - UDES_VERSION=14.0

services:
  - docker

before_install:
  - docker build -t ${TRAVIS_REPO_SLUG}:${UDES_VERSION} .

script:
  - docker run -i -t --rm ${TRAVIS_REPO_SLUG}:${UDES_VERSION}

before_deploy:
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

deploy:
  - provider: script
    script: docker push ${TRAVIS_REPO_SLUG}:${UDES_VERSION}
    on:
      branch: ${UDES_VERSION}
